spring:
  application:
    name: chef-mgmt-mail
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: ff61e4e8d71e4e
    password: 69f3d7a3e2a127
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  port: 8888
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false
queues:
  async-mail-sender-request: async-mail-sender-request